CREATE DATABASE IF NOT EXISTS rovena CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'rovena'@'%' IDENTIFIED BY 'rovena';
GRANT ALL PRIVILEGES ON rovena.* TO 'rovena'@'%';
FLUSH PRIVILEGES;
